### ISSUE TITLE
Энэ яг яадаг төсөл вэ?

### ISSUE THREAD

**Issue by redaced** [Jaha96/micromouse#1]
Зорилго нь юу юм сонирхолтой нэртэй юм байна

**Comment by Jaha96** [comment]
Энэ [https://www.youtube.com/watch?v=atMkFBfvSNU](url) бичлэг дээр байгаа уралдааны цаад талын самбард гарж байгаа Timer-ийг хийх зорилготой эхлүүлж байгаа юмаа
